
-- CONSULTAS DE VERIFICACIÓN
SELECT * FROM DOCENTE;
SELECT * FROM TELEFONO_DOCENTE;
SELECT * FROM RECURSO;
SELECT * FROM EQUIPO_INFORMATICO;
SELECT * FROM SALA;
SELECT * FROM DISPOSITIVO_MULTIMEDIA;
SELECT * FROM ACCESORIO;
SELECT * FROM PRESTAMO;
SELECT * FROM RESERVA;
SELECT * FROM INCIDENTE;


-- Consultas de ejemplo

SELECT 
    r.codigo,
    r.nombre,
    r.estado,
    r.ubicacion,
    dm.resolucion,
    dm.tipo_conexion
FROM RECURSO r
INNER JOIN DISPOSITIVO_MULTIMEDIA dm ON r.codigo = dm.codigo;

